// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '', // hidden for security reasons
    appId: '1:937800947619:web:d0e15507807d6c09c76c16',
    messagingSenderId: '937800947619',
    projectId: 'esof2324-6e8a4',
    authDomain: 'esof2324-6e8a4.firebaseapp.com',
    storageBucket: 'esof2324-6e8a4.appspot.com',
    measurementId: 'G-5VRBY1Y8EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '', // hidden for security reasons
    appId: '1:937800947619:android:e5fd8e8ac0b491b2c76c16',
    messagingSenderId: '937800947619',
    projectId: 'esof2324-6e8a4',
    storageBucket: 'esof2324-6e8a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '', // hidden for security reasons
    appId: '1:937800947619:ios:8c583c5cbfcf8866c76c16',
    messagingSenderId: '937800947619',
    projectId: 'esof2324-6e8a4',
    storageBucket: 'esof2324-6e8a4.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '', // hidden for security reasons
    appId: '1:937800947619:ios:d7fbedbf992ededdc76c16',
    messagingSenderId: '937800947619',
    projectId: 'esof2324-6e8a4',
    storageBucket: 'esof2324-6e8a4.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
